apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: day1-foundation
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: https://github.com/gorttman/day1-foundation.git
      targetRevision: main
      path: apps/coredns
    - repoURL: https://github.com/gorttman/dns/coredns.git
      targetRevision: main
      path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
