apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-exports
  namespace: infra
  labels:
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/part-of: day1-foundation
data:
  exports: |
    /srv/nfs/rpios/12.12 192.168.1.0/27(rw,sync,no_subtree_check,insecure,no_root_squash,fsid=1)
    /srv/nfs/cluster      192.168.1.0/27(rw,sync,no_subtree_check,insecure,no_root_squash,fsid=2)
