apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: infra
  labels:
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/part-of: day1-foundation
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-server
        app.kubernetes.io/part-of: day1-foundation
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values: ["arm64"]
                  - key: node-role.kubernetes.io/control-plane
                    operator: In
                    values: ["", "true"]

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: nfs-server
          image: gists/nfs-server:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - containerPort: 2049
              protocol: TCP
            - containerPort: 2049
              protocol: UDP
            - containerPort: 111
              protocol: TCP
            - containerPort: 111
              protocol: UDP

          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eux
              echo "=== Using /etc/exports from ConfigMap ==="
              cat /etc/exports || true
              exportfs -ra
              echo "=== Exported volumes ==="
              exportfs -v
              echo "=== Starting rpcbind & NFS daemons ==="
              /sbin/rpcbind
              /usr/sbin/rpc.nfsd
              echo "rpc.nfsd started OK"
              exec /usr/sbin/rpc.mountd --foreground

          volumeMounts:
            - name: nfs-data
              mountPath: /srv/nfs
            - name: exports
              mountPath: /etc/exports
              subPath: exports
            - name: nfsd
              mountPath: /proc/fs/nfsd
      volumes:
        - name: nfs-data
          hostPath:
            path: /srv/nfs
            type: DirectoryOrCreate
        - name: exports
          configMap:
            name: nfs-exports
            items:
              - key: exports
                path: exports
        - name: nfsd
          hostPath:
            path: /proc/fs/nfsd

          volumeMounts:
            - name: nfs-data
              mountPath: /srv/nfs
            - name: exports
              mountPath: /etc/exports
              subPath: exports
            - name: nfsd
              mountPath: /proc/fs/nfsd
      volumes:
        - name: nfs-data
          hostPath:
            path: /srv/nfs
            type: DirectoryOrCreate
        - name: exports
          configMap:
            name: nfs-exports
            items:
              - key: exports
                path: exports
        - name: nfsd
          hostPath:
            path: /proc/fs/nfsd
