apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: infra
  labels:
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/part-of: day1-foundation
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-server
        app.kubernetes.io/part-of: day1-foundation
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values: ["arm64"]
                  - key: node-role.kubernetes.io/control-plane
                    operator: In
                    values: ["", "true"]

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: nfs-server
          image: gists/nfs-server:latest
          securityContext:
            privileged: true

          # --- ✅ Entrypoint override to kill the built-in /nfs-share logic ---
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eux
              mkdir -p /srv/nfs
              echo "/srv/nfs *(rw,sync,no_subtree_check,no_root_squash,insecure)" > /etc/exports
              echo "=== /etc/exports contents ==="
              cat /etc/exports
              exportfs -ra
              echo "=== Exported volumes ==="
              exportfs -v
              echo "=== Starting rpcbind & NFS daemons ==="
              /sbin/rpcbind
              /usr/sbin/rpc.nfsd --no-nfs-version 2 --debug 8
              exec /usr/sbin/rpc.mountd --foreground --debug 8

          ports:
            - containerPort: 2049
              protocol: TCP
            - containerPort: 2049
              protocol: UDP
            - containerPort: 111
              protocol: TCP
            - containerPort: 111
              protocol: UDP

          volumeMounts:
            - name: nfs-data
              mountPath: /srv/nfs

      volumes:
        - name: nfs-data
          hostPath:
            path: /srv/nfs
            type: DirectoryOrCreate
