apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: infra
  labels:
    app.kubernetes.io/name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: nfs-server
          image: gists/nfs-server:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - containerPort: 2049
              name: nfs
            - containerPort: 111
              name: rpcbind
          volumeMounts:
            - name: nfs-data
              mountPath: /srv/nfs
            - name: nfsd
              mountPath: /proc/fs/nfsd
          env:
            # These are optional, but useful for visibility
            - name: TZ
              value: "Australia/Melbourne"
          args:
            # Launch sequence ensures exports applied, rpcbind & NFS started
            - /bin/sh
            - -c
            - |
              echo "=== NFS SERVER STARTUP ==="
              cat /etc/exports
              exportfs -ra
              echo "=== Active Exports ==="
              exportfs -v
              rpcbind
              rpc.nfsd 8
              exec rpc.mountd --foreground
      volumes:
        - name: nfs-data
          hostPath:
            path: /srv/nfs
            type: DirectoryOrCreate
        - name: nfsd
          hostPath:
            path: /proc/fs/nfsd
            type: Directory
