apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syslog-storage
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi

