apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-namespace
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: day1-foundation
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/gorttman/day1-foundation.git
    targetRevision: main
    path: apps/infra-namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
