apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxe-http
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pxe-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pxe-http
        app.kubernetes.io/part-of: day1-foundation
    spec:
      # ✅ Host networking for PXE boot delivery
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 8081
              name: http
          volumeMounts:
            - name: netboot-files
              mountPath: /usr/share/nginx/html/netboot/rpi5
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
          # ✅ Restrict nginx to eth0 only
          command: ["/bin/sh", "-c"]
          args:
            - |
              ETH_IP=$(ip -4 addr show eth0 | grep -oP '(?<=inet\\s)\\d+(\\.\\d+){3}')
              echo "server { listen ${ETH_IP}:8081; root /usr/share/nginx/html; location / { autoindex on; } }" > /etc/nginx/conf.d/default.conf
              exec nginx -g 'daemon off;'
      volumes:
        - name: netboot-files
          configMap:
            name: pxe-http-config
        - name: nginx-config
          configMap:
            name: pxe-http-nginx-config
