apiVersion: v1
kind: ConfigMap
metadata:
  name: pxe-http-files
  namespace: infra
data:
  boot.ipxe: |
    #!ipxe
    dhcp
    set base-url http://192.168.1.10/images
    kernel ${base-url}/vmlinuz initrd=initrd.img root=/dev/nfs nfsroot=192.168.1.10:/nfs/rootfs rw ip=dhcp
    initrd ${base-url}/initrd.img
    boot
  index.html: |
    <html><body><h1>PXE HTTP Boot Server</h1></body></html>
