apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxe-http
  namespace: infra
  labels:
    app.kubernetes.io/name: pxe-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pxe-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pxe-http
    spec:
      hostNetwork: true
      containers:
        # ------------------------------
        # NGINX container for HTTP boot
        # ------------------------------
        - name: nginx
          image: nginx:1.25-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
              name: http
          volumeMounts:
            - name: netboot-files
              mountPath: /usr/share/nginx/html/netboot/rpi5
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting nginx on eth0..."
              exec nginx -g 'daemon off;'

        # ------------------------------
        # TFTP sidecar container
        # ------------------------------
        - name: tftp
          image: ghcr.io/gorttman/tftp:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
          ports:
            - containerPort: 69
              protocol: UDP
              name: tftp
          volumeMounts:
            - name: netboot-files
              mountPath: /tftpboot
              readOnly: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              ETH_IP=$(ip -4 addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1)
              echo "Binding TFTP to ${ETH_IP}:69"
              exec in.tftpd --foreground --verbose --secure --listen --address ${ETH_IP}:69 /tftpboot

      # ----------------------------------------------------
      # Volume definition (shared host directory)
      # ----------------------------------------------------
      volumes:
        - name: netboot-files
          hostPath:
            path: /var/www/html/netboot/rpi5
            type: DirectoryOrCreate
