apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxe-http
  namespace: infra
  labels:
    app.kubernetes.io/name: pxe-http
    app.kubernetes.io/part-of: day1-foundation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pxe-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pxe-http
        app.kubernetes.io/part-of: day1-foundation
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: netboot-files
              mountPath: /usr/share/nginx/html/netboot/rpi5
              readOnly: true
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: netboot-files
          hostPath:
            path: /var/www/html/netboot/rpi5
            type: Directory
