---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgALqrIhfnURyc6+f8s4FDVfSKgIgTsq8S5pEyLJ40sF2v6OL0yGcxQtjEZMWSrLLXjNDq7tVt2FKqkRgY4Bu5mKw2WYNKA6EeUwR9NbuJaRpbCKlKCBDoPYZ53R0n5jsMRN366Z+7RlDDWMXs2glrfOL0yTeruc+voi1dyO1mBAvFYGxzuzd+WdUgeVMPeFyDf7AKrdv9mOV1nANm3qMSN/0gjMCVb/h5s7xxWTgkII4oVuCQusLOfdqcAI75mun7ZnKnrA9f/9P9tbY8ms7hY6A4hGwqx6lT8Qh25/7OuFwOGg0PuJqlII5ipVBXnLl7weI7Vb89eB0dog41kna6ICa26YFoUWY2nPEoqI2I81HHOwQc4Hc0BvsDVd9GvKY22tkRhFriJa8RCmVet4HIiPCz/6cBa5kQXbZtnntWhpYs0j6CAfjHILYIj+ZIlwXcoPd/6zoN/c8jkdbmu/BPEPkRUOUwxCidHBH8g3U7u4QNQP+q7E5bXtPkXggxmvKXKFbESmSGzatOySfymksYAkVEr2ukaZESA+EqIfAj2j0GODzM/h+dbV1/C7B8JV2eQmRZIzTqGVhYAZjWtEXW1/KGSV7hYwt3o/ySgLD6MDa7xHVyHKOreTbZg7LMM+CarBhxH4qnLY1pVrrSsBXRGY/FiLPYMoXWOoOuttDBgB7IizgfxS03emMwDcGcd+u7UmFXvO7q2IGdiTyAMNh0GdE00dmT0vvIRihaHMGvJ3RA==
    admin-token: AgC/a7l/efyc9x5wagIW4RYs67V0wV5rWSEr7uiMxmW17LNJ2V+8Xb5U6VJ8ADc+H5vtzhxF7KpHmljf2d+8unPq186Bj5ZNxgAzVyGK4mswg5/LhIkIngJUQDszW731knwwbK91IdGwffYHkVf5UW/bJjGJJ3j9n5/VhSLrDNBqll6niOeCjJEBhxmdW7Jc1EqR+A1vR5NVPUH8bbdPzxSx87v0eQeJZoGsqQjhMD/U6OEq3Cd0S11s2Or0FeEWjb1Exu3mFWpWoDAB5sB8uuNzANyjZ8f4pONY/UkDiJQYcanxkgiG1PRYDfUV7cAanE8oc8qn53P83FPob80/BQ2qmu3udjS2RNUc4Orkk5RPSqUu9P7zshWaKHurwBzXXcTr0ublJkMhFvrnWmKDWci8g6PMnEzvdRg2CXRZNXFW+Ug+nmK95c+fj08a4nAkDZBLe8n/qjymabmk92tfSqZr4viwBvtY3BKxB58SBt9RxnbixK/SY4A0xo6nbSnKwnErBlHD2YHFMoyc3AK+yiztoFbHsNR3AqAuWvDIAZmor6QVte5zVwW5JZ6q0g50F5X9Ju46tFq4mnaJZ3tHIsys4odwOjDmqpmUm8UdBzbSBS8W1joqABQ8StS5+9bMiVT18ft0+UHoy2jsakoVURy+POQp6LqX4warHf1l3zgyEe3221asgjv+NYSfsWSamKKWnkcnPxuRbB44XktRI6fFgLOdv1vFHYtlMq2R1G5BNV03DCeweqiTmbyeVWTi/UWJtJuCkX4+6UmjAkamif2Z
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: monitoring
    type: Opaque
