apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: monitoring
  labels:
    app: influxdb
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: observability
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # IMPORTANT: Replace this with a SealedSecret before committing to Git
  # Generate with: openssl rand -base64 32
  admin-password: "changeme-use-sealed-secret"
  # Initial admin token (used for API access)
  # Generate with: openssl rand -hex 32
  admin-token: "changeme-use-sealed-secret-token"

