---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA0Gdo/edsTtRqj1SQVcDFuS7w0L5ELcUzwfZYBxvXBtiI59MKPInHDMjPj3zYHYymqY+a5vCV6Mr2FXWVgz54nQEaXdKMo7d+ZdTC4/I9Rhd6LUlaOzy60tVTJzdTI/CSRWr2JtF5nrKyf4cIHcP7qiXW/3e0doT4hIMkTzPeFGgEYoWcxayiLhyAK2iKanXM70S20lh3O0v+72bH0LeJt+88Ic7aJUT+ASNoouhKsSqB+IpiHb33aTNSuIrVT4spuhTbtncuRFREaroTqwSB+ENsMpyxsPjRg/U07sUqKHbvlXp6WNF9UsVPlSxw+kx3d0l/QEsP2NAOdWVfI1HUG0fUuZ6VzmHxksYDwb5E7Bn4sI0uXFtriJ0SQYpD6dUgQ7vDnS7ZM/DwuwR+kCy7zjI2Wx2u0m7qeg+cQlKd8n/U/QvGlBuVdL5i3AgIiBssfG7f/AcKvV5D5kJE4FoOQNNcUelfl/7MjNLaz5bWNv59jZyopKl/DJapyq44YcAeb9MJf3W1nOaWMKwxLKhE7NQtDkXu2UeK2sDVkNbMAkvruH80YQj9flurIqVh/2xZ2Ip1V/8vlMKXgBUwMweMLM59g0GKmBQbiFWf+rtByGwBMk890Xxvpy/RCFqsBNKkvpNfJmDiTZVlpMOaS/ZDbWqrJ9CcHiS3tMxFvEyw3/kdHl9dQNZ+00cOQJ6OfVsbD/lv3AT/OiNBmQFo6WUJQkkFNGT8MqNErdk7x5MgvPA==
    admin-token: AgA1EglVyWp+CpcCOZ6d9u6f59xGXWNxjV4Ou5x0wrQGL5Cg0gFYO8Cqdcd39vnpFpVpveGJdA8ahnpIknrFVe6MgZf5dYHWurV83d7BmOr2Exr7qOQ7m8JFjc915PQUOOi8dfi51pK7saLMsUFXhx/jqqbUubdZLZfiG/AsgWNtQOoaxIsxPBU3NEE82QekZvNI/BAwQO7R2UNG76LVjBEdiQ52fm7rHqzGyojLSkkSQC1Wrq0LT0+2uuSopQYP7l/KqUh+mkdtrMpXzRPMcsSE7kWTvIWy8m+2pI3tWNoy2C8OLoMl4y6ysntp2g0qpr9PXOEfC0omTTPkEj4ko+75eGtTpCnSvuxVrbTkBjiJTxftUHbyeU+RNPbXyN1aqFMoxMOOjX8IanddICQ9Y/ZinXnvayw9nhJZ1itbM6JpFmCf52m/DsnfZf07osIUwpYL7nu6Y1aBjBir+tn1/OCHWDF3gtrlRlH8W24cJRnn8WF1tYLCJNV0ehhzu9bbEns8sf9SZwutawXQE04d8b5mmJTUu9ZLTnPUA47N8CJqTuJdOgycrgbfG7P99B9LYBel0Of9Q3KHkQbaQsuV2AXAlbS7LDkVgogDIU9gaViJClfE8mzRxFyqWIn793wFTPOSSunmxret9Ey96z/ScAKAtPnnA8OLeztPO2W8DvXcKWO6hEhw2YRFrnR+CNfzTx7qPQYdTTyHtGG/7WS98wx15BnP96VRtmT2STavQMwhK+IGWcGoe8kuKZBhDszhTek5bu8vOlifRkZHvqNLVw+O
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: monitoring
    type: Opaque
