apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: observability
    argocd.argoproj.io/managed-by: argocd
  annotations:
    cert-manager.io/cluster-issuer: "private-ca"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - influxdb.i3sec.com.au
    secretName: influxdb-tls
  rules:
  - host: influxdb.i3sec.com.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: influxdb
            port:
              number: 8086
