apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - qnap-books-pv.yml
  - qnap-vault-pv.yml
  - qnap-immich-pv.yml
  - qnap-paperless-pv.yml
  - qnap-pihole-pv.yml
  - qnap-calibre-web-backup-pv.yml
  - qnap-pihole-live-pv.yml
  - qnap-calibre-web-live-pv.yml
