apiVersion: v1
kind: Secret
metadata:
  name: log-archiver-secret
  namespace: logging
type: Opaque
stringData:
  NAS_MAC_ADDRESS: "00:08:9b:bb:ee:da"
  NAS_IP_ADDRESS: "192.168.1.30"
  NFS_EXPORT_PATH: "/srv/nas/logs"
  ARCHIVE_DAYS: "3"

