apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-archiver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gorttman/day1-foundation.git
    targetRevision: main
    path: apps/log-archiver
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

