apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client  # Uses your NFS provisioner
  resources:
    requests:
      storage: 2Gi  # Blocklists, logs, config

