apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/   # upstream Helm repo
    targetRevision: 2.27.0                                  # pick version
    chart: pihole
    helm:
      values: |
        replicaCount: 1
        serviceWeb:
          type: NodePort
          nodePort: 30500
        serviceDns:
          type: NodePort
          nodePort: 30501
        # point persistentVolume to your NFS provisioner later
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
