# apps/portainer/portainer-service.yml
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: NodePort
  selector:
    app: portainer
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 30900
  - name: https
    port: 9443
    targetPort: 9443
    nodePort: 30943
  - name: edge
    port: 8000
    targetPort: 8000
    nodePort: 30800
