[agent]
  interval = "30s"
  flush_interval = "30s"
  round_interval = true
  skip_processors_after_aggregators = true
  omit_hostname = false
  hostname = "$NODE_NAME"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb.monitoring.svc.cluster.local:8086"]
  token = "$INFLUX_TOKEN"
  organization = "pilab"
  bucket = "telegraf"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.temp]]

[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

[[inputs.net]]
  interfaces = ["eth*", "end*", "wlan*"]

[[inputs.kubernetes]]
  url = "https://$HOST_IP:10250"
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  insecure_skip_verify = true
  namepass = ["kubernetes_node", "kubernetes_pod_container"]
