[agent]
  interval = "60s"
  flush_interval = "60s"
  round_interval = true
  skip_processors_after_aggregators = true
  omit_hostname = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb.monitoring.svc.cluster.local:8086"]
  token = "$INFLUX_TOKEN"
  organization = "pilab"
  bucket = "telegraf"

[[inputs.prometheus]]
  urls = ["http://influxdb.monitoring.svc.cluster.local:8086/metrics"]
  metric_version = 2
  fieldinclude = ["go_goroutines", "go_memstats_alloc_bytes", "process_resident_memory_bytes", "http_api_request_duration_seconds_count", "http_api_request_duration_seconds_sum"]
  [inputs.prometheus.tags]
    service = "influxdb"

[[inputs.prometheus]]
  urls = ["http://argocd-metrics.argocd.svc.cluster.local:8082/metrics"]
  metric_version = 2
  fieldinclude = ["argocd_app_info"]
  [inputs.prometheus.tags]
    service = "argocd"

[[inputs.prometheus]]
  monitor_kubernetes_pods = true
  monitor_kubernetes_pods_method = "settings"
  monitor_kubernetes_pods_scheme = "http"
  monitor_kubernetes_pods_port = 9500
  monitor_kubernetes_pods_path = "/metrics"
  monitor_kubernetes_pods_namespace = "longhorn-system"
  kubernetes_label_selector = "app=longhorn-manager"
  metric_version = 2
  fieldinclude = ["longhorn_volume_robustness", "longhorn_volume_actual_size_bytes", "longhorn_volume_capacity_bytes", "longhorn_node_storage_usage_bytes", "longhorn_node_storage_capacity_bytes"]
  [inputs.prometheus.tags]
    service = "longhorn"

[[inputs.prometheus]]
  urls = ["http://cert-manager.cert-manager.svc.cluster.local:9402/metrics"]
  metric_version = 2
  fieldinclude = ["certmanager_certificate_expiration_timestamp_seconds", "certmanager_certificate_ready_status"]
  [inputs.prometheus.tags]
    service = "cert-manager"
