apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<org>/day1-foundation
    path: apps
    targetRevision: main
    directory:
      recurse: true  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
