---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-telegram
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgCNlKwyNal8reXJLhAEp+r3xT12gwtc+IQL5gAwspVA7Du2uRkK20Ry9F7IDt2GNZF2vqglKuW6/9rtWMXPWMl4mZk5aer7FplMy13OZnxaKMxbWjFu31sOASsSUAS1cfzX0w/yTIbwuCHeXs7hdxa6tKQtTnkBlNpOtm5M7F3OxwEszJ5XUcXRcQpACdUPBm4h1Nl7RDitaNDTP4NFl5CgwmVYp1oy2M1B30RSLJRUSygmHTYkvGPA4JBmBEt05ye7mlMzITTYdd8FEmAWE+SAzkiZkXO3cCX1vYuRB3Y76qlCkRTQZ7QYIkSpkOCcenKWXaLFxYvgyhwP0Qzku0axXJ9CLLZM5hoBc2VdjV7TDCR7y2zZpHwJ1vIgoPKEhljHCTARLR2/d/KbRrlvvXOibGZehMHQFiWfUt8ztCN0s9QpkGTbavpl89KqIQbwl7e9ApmyTw936lhjJ3bbuL1u3KBWSiUbMD8QMMjWCOQb6GRF2sk0KSHYXHV+S7tmjkTP8zUz+tz9Xauw1u5tJMrC1Hdj0eTxGSFrDpul5xXqxW0OG1434WS8xgMUBnPi/aHJe1anIGWOlCnugMO7QBFsuGIqyQ+f6iKnaz8pNzQTf0o2FhdlqiBQ969CcZW6K7Gm5y+Qsyv9AkP+tVBLmcg8gX8r2cL3SAislpj2zsJd7je3XvLdrPL00jmBDlIKtcjo7ypcVPoZU8M6Z23qXR8/72Z/BjKl6WyN9AFc+qJhimr6YQ6DzBnRKfNCH5E5
    TELEGRAM_CHAT_ID: AgBjhgGyI6enM1tyBLpeuzllSzgdHgZq4K992EhcSs/kBXPqd1JQHgWSO7QLlI3rbpX80S6+7jlsWCLZh17v9evhK4b6NHXVzLhmBo01lZHBYOvLNyD7DbirjvVhu1IUcKVZvJpecy4ZSFUQ/h9kdhcj1Lpm33Fgr3F+XULNyGWBVO7oOFGU+tTDeh5akQ3ilZgkHxc6FfcaQLM47BL6LxGxmt9Wqvr4sk5PQw36GhEPVjbaUmhY6dRf/nZO0SbdL89kariNVbq3baG0l7ZgX7QdXnEiFQde0HaEKJ/oz3dm2X4MWnNTIEfk3KcafYya+2V7pop4wnHdXMWBBOGcst33ltYx0VTFddsgJTSR9S8qKMvtuVlqhKHongXZBfeOx6tH5StRzXfpOLMNivHDPAw6bJ/soTc/xNIvEdOxxS6fuEVdP234H5VxafzfntryfduiYtTpJgHoxzcoUuWkACyy4/ofJiunHTjN48Lgrvfv8cRfqaN6vI6C+26RECDatDSgjDpeyPefIET1/LMHfpYMxIvjEbi+2gLtmlqfxgcgKZ9TGRRmjQtk3Y+FRv1Ozf8cgFxqo4SS326wRf8BiAK4IKgylHaseBfopXDcYNVxn0ZsA9uPOVPm7yj+4SyG2V0fpjA+uGBRgAvCV8FPXN8TJC6x+0ki+PHLGo4ByHuJx2BAftgWLb20rdo88fD8hyx8YAYCZ6Hz4o7E
  template:
    metadata:
      creationTimestamp: null
      name: grafana-telegram
      namespace: monitoring
    type: Opaque
