apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcpd
  namespace: infra
  labels:
    app.kubernetes.io/name: dhcpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dhcpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhcpd
    spec:
      # --- critical: allows raw L2 access ---
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      containers:
        - name: dhcpd
          image: networkboot/dhcpd:latest
          imagePullPolicy: IfNotPresent

          # --- full privilege and capabilities for L2 broadcast ---
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW

          args:
            - /usr/sbin/dhcpd
            - -f
            - -d
            - -cf
            - /etc/dhcp/dhcpd.conf
            - eth0

          volumeMounts:
            - name: dhcp-config
              mountPath: /etc/dhcp
            - name: dhcp-leases
              mountPath: /var/lib/dhcp

      volumes:
        - name: dhcp-config
          configMap:
            name: dhcpd-config
        - name: dhcp-leases
          emptyDir: {}
