apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcpd
  template:
    metadata:
      labels:
        app: dhcpd
    spec:
      containers:
        - name: dhcpd
          image: networkboot/dhcpd:latest
          args: ["-f", "-cf", "/etc/dhcp/dhcpd.conf"]
          volumeMounts:
            - name: dhcpd-conf
              mountPath: /etc/dhcp
      volumes:
        - name: dhcpd-conf
          configMap:
            name: dhcpd-conf
