apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcpd
  namespace: dhcpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcpd
  template:
    metadata:
      labels:
        app: dhcpd
    spec:
      containers:
        - name: dhcpd
          image: networkboot/dhcpd:latest
          args: ["-f", "-cf", "/etc/dhcp/dhcpd.conf"]
          volumeMounts:
            - name: dhcpd-conf
              mountPath: /etc/dhcp
              readOnly: true
      volumes:
        - name: dhcpd-conf
          configMap:
            name: dhcpd-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dhcpd-conf
  namespace: dhcpd
data:
  # This pulls from the *second source repo* in dhcpd-app.yml
  dhcpd.conf: |
    #@include config/dhcpd.conf
