apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcpd
  namespace: infra
  labels:
    app: dhcpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcpd
  template:
    metadata:
      labels:
        app: dhcpd
      annotations:
        checksum/dhcpd-config: "{{- .ConfigMap.data.dhcpd.conf | sha256sum -}}"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: dhcpd
      nodeSelector:
        kubernetes.io/hostname: pi-1   # pin to backend NIC node
      containers:
      - name: dhcpd
        image: networkboot/dhcpd:2.4.5-arm64
        imagePullPolicy: IfNotPresent
        args: ["-d", "-cf", "/etc/dhcp/dhcpd.conf", "-lf", "/var/lib/dhcp/dhcpd.leases", "eth1"]
        ports:
          - containerPort: 67
            protocol: UDP
        volumeMounts:
          - name: dhcpd-config
            mountPath: /etc/dhcp
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN", "NET_BIND_SERVICE", "NET_RAW"]
      volumes:
        - name: dhcpd-config
          configMap:
            name: dhcpd-config
