apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcpd
  namespace: infra
  labels:
    app.kubernetes.io/name: dhcpd
    app.kubernetes.io/part-of: day1-foundation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dhcpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhcpd
        app.kubernetes.io/part-of: day1-foundation
    spec:
      serviceAccountName: dhcpd

      # DHCP must listen to broadcasts on the real LAN
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      # Affinity: must be arm64 arch AND either control-plane OR master role label
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values: ["arm64"]
                  - key: node-role.kubernetes.io/control-plane
                    operator: In
                    values: ["", "true"]
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values: ["arm64"]
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values: ["", "true"]

      # Tolerations so it can run on tainted master/control-plane
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: dhcpd
          image: networkboot/dhcpd:1.3.0
          imagePullPolicy: IfNotPresent

          # Bind only to the correct backend NIC
          args:
            - "-4"
            - "-f"
            - "-cf"
            - "/etc/dhcp/dhcpd.conf"
            - "eth0"   #  corrected interface

          ports:
            - name: dhcp
              containerPort: 67
              protocol: UDP

          volumeMounts:
            - name: dhcpd-config
              mountPath: /etc/dhcp
              readOnly: true

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE"]
            runAsNonRoot: false
            runAsUser: 0

          readinessProbe:
            exec:
              command: ["sh", "-c", "dhcpd -t -cf /etc/dhcp/dhcpd.conf >/dev/null 2>&1"]
            initialDelaySeconds: 2
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 2

          livenessProbe:
            exec:
              command: ["sh", "-c", "pidof dhcpd >/dev/null 2>&1 || exit 1"]
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi

      volumes:
        - name: dhcpd-config
          configMap:
            name: dhcpd-config   # always plain name (we disabled hash in dhcpd-conf)
