apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcpd
  namespace: infra
  labels:
    app.kubernetes.io/name: dhcpd
    app.kubernetes.io/part-of: day1-foundation
  annotations:
    # Force a "replace" so removed fields (like old volumes) are truly removed server-side
    argocd.argoproj.io/sync-options: Replace=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dhcpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhcpd
        app.kubernetes.io/part-of: day1-foundation
    spec:
      serviceAccountName: dhcpd
      nodeSelector:
        pi-lab.io/role: infra
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: dhcpd
          image: ghcr.io/gorttman/dhcpd:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "-f"
            - "-cf"
            - "/etc/dhcp/dhcpd.conf"
            - "-lf"
            - "/var/lib/dhcp/dhcpd.leases"
          ports:
            - name: dhcp
              containerPort: 67
              protocol: UDP
          volumeMounts:
            - name: dhcpd-config
              mountPath: /etc/dhcp
              readOnly: true
            - name: dhcpd-leases
              mountPath: /var/lib/dhcp
          securityContext:
            capabilities:
              add: ["NET_ADMIN","NET_RAW","CAP_NET_BIND_SERVICE"]
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: dhcpd-config
          configMap:
            name: dhcpd-config
        - name: dhcpd-leases
          emptyDir: {}
