apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dhcpd-conf
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/gorttman/dhcpd-conf.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dhcpd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
