---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gorttman-git-pat
  namespace: argocd
spec:
  encryptedData:
    password: AgBOYR9Y+a7fXtyWOliK92Ce49oqYGDSVod5gly2g7cGL2FZHejI8gJ0hcN+Qinw1SSTVajhEhL1YBwcK27kw3KzW8Y1phf0GvnSW2qnu5/db2kecLMKXjHTQ/70xP9mFmXYK4OVkk7mlq9iAQtYd/0ayu1hNjjwcGil5fBjq0hP4QTBrlzVRaFcrJ2aM5VJ+uVoirUCpm1c1fHO9yCKgUtfLnUi9MygXnj4Ce2SkDXgi5fscrfWDuMwlITJ1l+dEZmlwZ2QruaWkr7H+FBmGZv9bbvpa4BWxr93eWKHDs8IR6G+QDK3SJ+6KpzQ/3aKhXfacR8eDC3gMbhtJQPlXkhuWGbEgE9SLx0gpmquGgTdrfK3z5NFkt79Ordq8eQ3PioH/Q7EC9GIMK/1SvDUbOO7mPmf6GSJGfQCQslIndyMvGP5RR3ny0tvC9IyO912PpbjGWLbC2Wblbhe/CY2mJuORlmq2pUJOIbC9qG69F86h5asgVAfts8GYI3sv4gtnJ7yEdoD5fkbtygeukJyLxuZkqLyqdWBR2O1mIpXGm9iCsyHoIEuDcSroFX/yaeoBxN5HAdMM8GwaWmzmWDHAvgEtzBXrUKmRAHfT5ZJuRJCI9XeZ1+ZAwxcHJff2SkeK5/I++6LEZya+cd5V4LnzLNKTFJyCxnIwwkudXpvUxKM15kqMzYlilvQCcoQpu4mIfnllKWGWXzx1iIMkZF7Be+1jg==
    username: AgB6sSOI64U9ZRjY5MCp8QmHMpTfTinuwTTk+3XIQ0WuKc2CKIC1thwbzSzX08mzFgQ5xDe1WKd0++uXeBCRkbDqgDihbjuozICXPw8u0rNI6PYEv5o2CINEb7lvqTCDI99HGMteudGnjbW5UcoQGU4sE98qbkE3q9PEPQ8PWvqXkyl40t/ut+o6PEnokn3Lg/vevNXbpmb1YWvTBZxRr02WE0KyY52lUg+r/h234uhRbM4lgy1Xt0jEt8uAwnVDVFUUxHsMMvQKp0g4TYvx5mCIRLp/t0bxW3CQRt2GiMDxvBm2Thr4qd9GG/Z2tAJ2iYCBZHQNROganPxV6Fnbm9W3eRrRIsNJ3dRV+/zahtzBjlAlfVCh1wpkxbyE4FKT6PVDXOs6KVlVqWAeudMq4xNwcsSU3W6OvDgjrdl9A/K6OviUHo1lexjfL21aottrLjRTWDpmbwwqMwhnOco8TSrZBJQG+r9tYlLqj8StZiyADk2nSTU2dz4vjxvvi57tOdfKpYNPd0ZAJMDPwVPyUoai+twXFuZtrCu7P9JBiNV4t4kw9TxTKpym3gXyL/sB3bQQuMoneyYtCTCq99MjM9iI1EOoYWDWwNu0U7RWWgl9HEV3k1S0tE69NvZrnu2IOQVoR0luPMu9PVstgDObdGH0dHpHSELD+c6F0zKMYzXb77csr9LVID4zSYArqFCD3BABcnk=
  template:
    metadata:
      creationTimestamp: null
      name: gorttman-git-pat
      namespace: argocd
    type: Opaque
