apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dhcpd-namespace.yml
  - dhcpd-serviceaccount.yml
  - dhcpd-role.yml
  - dhcpd-rolebinding.yml
  - dhcpd-deploy.yml

configMapGenerator:
  - name: dhcpd-config
    files:
      - dhcpd.conf=dhcpd-conf/dhcpd.conf
generatorOptions:
  disableNameSuffixHash: true
