apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - dhcpd-serviceaccount.yml
  - dhcpd-role.yml
  - dhcpd-rolebinding.yml
  - dhcpd-deploy.yml

configurations:
  - kustomize-config.yml
