apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - dhcpd-namespace.yml
  - dhcpd-serviceaccount.yml
  - dhcpd-role.yml
  - dhcpd-rolebinding.yml
  - dhcpd-deploy.yml

# Private repo remote base (Argo uses repo Secret to fetch).
# If your default branch is not 'main', change ref=
resources:
  - github.com/gorttman/dhcpd-config?ref=main

# Ensure the hashed ConfigMap name is rewritten into the Deployment volume
configurations:
  - |-
    nameReference:
    - kind: ConfigMap
      fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/volumes/configMap/name
      - kind: Pod
        path: spec/volumes/configMap/name
