apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - dhcpd-namespace.yml
  - dhcpd-serviceaccount.yml
  - dhcpd-role.yml
  - dhcpd-rolebinding.yml
  - dhcpd-deploy.yml

configurations:
  - |-
    nameReference:
    - kind: ConfigMap
      fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/volumes/configMap/name
