---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgASddBm0YkzDo1Zuuq/2yjE5n+hCVOupGh2u4b7jS91xjH4nVdCz2mFZeV2vldNmLZKTE3yCmf5SmH5lP6dAiAvj25UtM0EkCy3qCgibJGcrSJbZvDsPkRxaAWGwCIx8nQv//v2GQuxlnqm7XBxe4MX0LqYdYaMOV9TtyP3DR3KXl7wav27VSkRHgy00fBZ6Lw1WP/uP1HDScwqh9w3mzK+LW03wwnD6wCp1MgUdsgyBLBw2frhx2fBdcqy8w61f/92hA5fuO3Rykmn915J+vo41XUT8jRO6cXPOD7euX63qRgbSBSO0sY4789TQA+uPJHtPm6QzCponhJjDFMRq1popTeZEYdMsvvZQPW/mF07SMMFRLf16MGs7NXBG9ptWWoLzDdED/zC70aG1SLRqo3nZy/IAzjnHRq71v4A6R7RNvGnvjsxQJn9XNVUIa1HJ3LQzbt2VBQow3ihEfVN+WPY5A3xK92ENJiGmn5gsrL4D3WNG6q+58Yn1348CIa5X7taV8KNBphPqHSiMY2Rpefv3KXhgp94vqH7c9J4e4oq9dTYA32OUkYT+uryh8i9PRVVb8jVPYUvwY+iiXG3Dk3gdLULGewI0nUTGILWzbnHhvkggwVZAPkYoWYfKiCrtLVP+MT2SYwnnNN4S+dewxLuT2Mtaaz/qVFqg606kp47is5uTXnfxd70hIFDKMpLMMs016KJyNEzFwyyB9DgYnt7uYemBrm5Z4uDMVuZsAJL55+ivfzMuQOYXMMVGb6Hutb12iSPKfs1FW4jbRTNe9kWGo+xkbGoheJbhCeO0s9K6WicMedcHhTL2G+C+LIhoObwmve5DFsDoYBKUahRB3/Kfu/RwTfjoWzS+EEE9CNMwNWsQv5khZ/fBBMrrwO1m2kxNixzSw/4pUAYG6kZi2bu6ikjrbsOhTf2DP/czcKDATVjGY6PUBT9
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
