---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAA60Gsr9uw86H7C3pWOfBzEInpA/sRdlibGTgPuxsTZjMUIo50MH/6e+8205nsYUDitip/tF7drBKze/1waktkDTMuFpch+gGubsUUcpGDqF9HmkdpmSNUVx8OdobzBG6+1xYqL7F9aR8afEDCL9llgTNyEh3a+ZJcdQ0KhpHp5IBElAQ1ahXV0SWMNedbVf1a7FZEw+mwH8DmMVeOdbOvIPAwMhz+0elSO1H/MQf9pqoxpXMSGah/x9RhxaxeSsinRka8REDoXP3pvXIDAcTFZPMeUrvZwnRUsayqLfxOHlliJonrnT3Fuon6IPlYTnjS+OuDfB5BAGE8uGWvU+QzlzjjXRKu16MfnaymepIIyIXFg1+pABfQgZ+HVljF0rpinO5DbqgUV9bPYgNEYzIjXYJHs4TOya5GmnQOUfyuOg0cs5AwcSbBjJNbNZNI63ZLkODzOaxEPW9+eHv6MwsVCQKMc6kK3SKbi6fBvk5DASDoeX3+vqX1l1LfwmLZeLsxM8ML6FiViiz8clYNH56Hbx8jsOtA6k4D22D4upUeIivreD56mvtehyHv9cGbuUS2hJkvxzGxUl44+RDgSnSxB8GCIHAqYiavy49dIlDSvMRkTYFDAAsABaeKWoQyn7PeFNdiLAQoUt1rU2TbzBY3rIe7d8FsYiJEFDmoNC1o+oR/InA7AaioIVPWqbvDQGxxYgZ9cpI6Pa0KLXwBT5ctsAvRoDAUGplGi9MBhQDRydoGn7zGNlkZEwMjHPJVe+g0ZcxaftZEPWjAVEGJk6CPLKwqWoYdJ+t3Wn6OvTXPj7dbDac/ihbD6hHnpGWcZT4Cn+Pq68p12q1R64RupmMRynC2ntTcaFmAZfd4QBqN0s0bfHVDF8CmmJWToZGx+PoOSUrr8pZ755ItznXxmgfm35vra50LPfhV9JdgK5SPC3F3nVhqcwTb
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
