---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegraf-influxdb
  namespace: monitoring
spec:
  encryptedData:
    INFLUX_TOKEN: AgDCuV08YcKa36sIy/A/vlFiNG7HMa3wpxsQOiMCAptxHxHH5lCU0Ngs3fRQM6PzM8kbTX0DJxozJYQzMwt4L+enCX+xkTxrsnD2yFJUHOhpvNvT2BTLm7u5PSHPBbSByh+V6DuCgn5/+NFO8K2UuvZdWnIJeT2VHXNw+mt+UGP2JI8PNBgR7KhHJrEF0uKUO8o3FFcho5PbSyCx4vZ9P/7KDUNN4TjGXCinOno34abfEfuDXJffM+RaEtOvHC5tbN7xHPoSBvne4xtmZM6qiPgd4kOoGLwdKMU/6d5k7Yz6RT9zQNm+EEzbZq18S7DvI41uYLrhOM+TcxwT9uaESl+brNFmwZz/ivXTYrYODoxrTxYRwTn9yZumkb12usNFhGzsPKUxg45QvXSV7YX9roiEvfSJ3nwynppALQQ/55PzNi4lsxyAG4MDm5m7aee13JORoBi2x1GhiPrQcQd+VYZbshlzUlBiimGtohyFTwmmcUplIYnFbeZbAC+sH7eDNCnB1rRgNrL+6I9/xlzYyEFis7n/PoqXlLKUBlLRHLuWXq/YiVTazfUg9ysJm0TILbTQMhNJhCNYoPPemK8NvtjjVMiTqReH9pIZbFT6t38iTbGx7flg3sxC4tk5wxfm0QLFk/86j4W8Hs6cYs08nrujdeZ9hcorVnMxJLGaA6xRO7f/e+XeEgKDIMlzBoA2OluVC9XAAS0m8O/9dnG4TO1w94goVHii6c/bomiJixIP4vJgmdbVgg+QtvMPjeSuOS6V26JFA+KI6/CoiDRVRRrwE4T1gb9/M7NT8wGHg8MMQI79bixi8ZOi
  template:
    metadata:
      creationTimestamp: null
      name: telegraf-influxdb
      namespace: monitoring
